language:
  - java

jdk: openjdk8

env:
  global:
    - NODE_VERSION="7"


# Stop travis from running mvn install (without profile)
install: true

before_install:
#  - mysql -u root -e "create database IF NOT EXISTS waltz CHARACTER SET='utf8';"
  - nvm install $NODE_VERSION
  - npm install npm -g
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS waltz;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE waltz;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mariadb' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS waltz CHARACTER SET='utf8'; fi"

script:
  - if [[ "$DB" == "h2" ]]; then mvn -s .lgtm.settings.xml  clean package; fi
  - npm run-script test --prefix ./waltz-ng

# Enable caching of dependencies
cache:
  directories:
    - $HOME/.m2
    - node_modules
    
# safelist
branches:
  only:
    - master
    - rel.*
    - /^waltz-.*$/


jobs:
  include:
    - stage: Test
      env: DB=h2

    - stage: Test
      env: DB=mariadb
      addons:
        mariadb: 10.1